play_media:
  name: Spotcast Play
  description: Play spotify media on chromecast devices
  fields:
    media_player:
      name: Media Player
      required: true
      selector:
        target:
          entity:
            - domain: media_player
              integration: cast
            - domain: media_player
              integration: spotcast
    spotify_uri:
      name: URI
      description: Supported Spotify URI as string
      example: spotify:album:5l5m1hnH4punS1GQXgEi3T
      required: true
      selector:
        text:
    account:
      name: Spotify Account
      description: The id of the spotify account to use. Takes the default account otherwise
      example: "pirate_jeanne"
      required: false
      selector:
        config_entry:
          integration: spotcast
    data:
      name: Data
      description: Additional modifiers for the play_media service call.
      required: false
      selector:
        object:
