blank_issues_enabled: false
contact_links:
  - name: Spotify Card
    url: https://github.com/mikevanes/spotify-card-v2/issues/new/choose
    about: You are experiencing issues with the Spotify Dashbord Card
